### ISSUE TITLE
🐛 Bug Can not handle img 

### ISSUE THREAD

**Issue by youngjuning** [JohannesKaufmann/html-to-markdown#25]
**Describe the bug**

**HTML Input**
```html
<figure><img class="lazyload inited loaded" data-src="https://i.loli.net/2020/08/13/cVomW7L9YOTw2uA.png" data-width="800" data-height="600" src="https://i.loli.net/2020/08/13/cVomW7L9YOTw2uA.png"><figcaption></figcaption></figure>
```

**Generated Markdown**
````markdown
<img class="lazyload inited loaded" data-src="https://i.loli.net/2020/08/13/cVomW7L9YOTw2uA.png" data-width="800" data-height="600" src="https://i.loli.net/2020/08/13/cVomW7L9YOTw2uA.png">
````

**Expected Markdown**
````markdown
nonting
````

**Comment by youngjuning** [comment]
demo on https://github.com/youngjuning/homebrew-juejin-spider/blob/master/juejin.go

**Comment by youngjuning** [comment]
fix it on my way： https://github.com/youngjuning/homebrew-juejin-spider/commit/fa99c0b63e83c41ad793e750dd36c8cd49544aea

**Comment by JohannesKaufmann** [comment]
I assume that you meant following html:
```html
<figure>
    <img
        class="lazyload inited loaded"
        data-src="https://i.loli.net/2020/08/13/cVomW7L9YOTw2uA.png"
        data-width="800"
        data-height="600"
        src=""     // empty?
        >
    <figcaption></figcaption>
</figure>
```
The "src" attribute is empty because the image is lazy-loaded. 

----


I have thought about using “data-src” automatically when “src” is empty.

But there are three problems:
1. "data-src" can filled with any data. It is not guaranteed to contain the url.
2. The image url could also be somewhere else, like “data-lazy-url”.
3. Some websites display a placeholder _(for example “blank.gif”, the colours of the image, or a really low resolution of the image)_ in the “src”. The library can't really find out which image url is better unless it loads the images...

----

@youngjuning  If you know the website and you know what the rules for lazy-loading are, I would recommend the following function:

```go
// The hook-function is called before the rules are run. You can change the html that is passed to the "img" rule.
conv.Before(func(selec *goquery.Selection) {
	selec.Find("img").Each(func(i int, s *goquery.Selection) {
		_, ok := s.Attr("src")
		if ok {
			return
		}

		s.SetAttr("src", s.AttrOr("data-src", ""))
	})
})
```
But your solution works as well 👍

**Comment by youngjuning** [comment]
@JohannesKaufmann Thanks for your answer，your are so 👍
