### ISSUE TITLE
🐛 Bug <br> is converted into two new lines (\n\n)

### ISSUE THREAD

**Issue by prologic** [JohannesKaufmann/html-to-markdown#40]
**Describe the bug**

In my testing I've found that the HTML tag `<br />` gets turned into two new lines (`\n\n`);

Example:

```#!sh
(⎈ |local:default)
prologic@Jamess-iMac
Mon Aug 02 11:37:55
~/tmp/html2md
 (master) 130
$ ./html2md -i
Hello<br />World
Hello

World
```

**HTML Input**
```html
Hello<br />World
```

**Generated Markdown**
````markdown
Hello

World
````

**Expected Markdown**
````markdown
Hello
World
````

**Additional context**

Is there any way to control this behaviour? I get that this _might_ be getting interpreted as a "paragraph", but I would only expect that if there are two `<br />`(s) or an actual paragraph `<p>...</p>`. Thanks!

**Comment by akuehnis** [comment]
According to this page (https://www.markdownguide.org/basic-syntax) a newline in markdown shall be formatted as follows:
To create a line break or new line (&lt;br&gt;), end a line with two or more spaces, and then type return.

I have also seen implementations where &lt;br&gt; and &lt;p&gt;&lt;/p&gt; are converted to one and two newlines (as prologic recommends).

I don't know if there is a real standard for this. However, &lt;br&gt; must be treaded differently than  &lt;p&gt;&lt;/p&gt; for not to loose information when converting from html to md.

**Comment by JohannesKaufmann** [comment]
Take this HTML as the input:
```html
<p>Line 1<br />Line 2</p>
````

With html-to-markdown and the normal commonmark behaviour for "br" with two newlines we get:
```md
Line 1

Line 2
````

With Commonmark (see [playground](https://spec.commonmark.org/dingus/?text=Line%201%0A%0ALine%202)) this renders as:
````html
<p>Line 1</p>
<p>Line 2</p>
````

<img width="933" alt="two_newlines" src="https://user-images.githubusercontent.com/20886667/236924607-c9a217d4-2f42-4e6c-bae2-99f85c3c724f.png">


----

If you add a custom rule for "br" that just returns a single newline with:
````go
return String("\n")
````

You get this ouput:
```md
Line 1
Line 2
````

With Commonmark (see [playground](https://spec.commonmark.org/dingus/?text=Line%201%0ALine%202)) this renders as:
````html
<p>Line 1
Line 2</p>
````

<img width="878" alt="one_newline" src="https://user-images.githubusercontent.com/20886667/236924950-166dead5-4d94-4028-8a02-9ec1ab3fbed0.png">


----

If we compare the different implementations (see [babelmark](https://babelmark.github.io/?text=Line+1%0ALine+2%0A%0A---%0A%0ALine+1%0A%0ALine+2)) this behaviour is mostly shared between implementations.

<img width="1037" alt="babelmark" src="https://user-images.githubusercontent.com/20886667/236926152-8e4c91cc-77ef-4f7b-a6b0-0851158de6a8.png">

The markdown rendering on github.com works differently however 🤷‍♂️

<img width="293" alt="github_dot_com" src="https://user-images.githubusercontent.com/20886667/236926191-9e151ed6-b755-4fae-a1a2-89f5e4935143.png">


---

If we want to be extra precise, the html-to-markdown library would need to also support _hard line breaks_. However that would require some other changes.

So for now, the current behaviour is going to stay as it is. Changing it would break it for other implementations. However you are free to change the behaviour, by writing a very simple custom rule.

**Comment by suntong** [comment]
> The markdown rendering on github.com works differently however

Then can we have the GitHub-flavored markdown to use single line breaks please?  
(without the need of hard line breaks, as the GitHub-flavored markdown is supposed to be tailored towards github.com)

Thanks

**Comment by JohannesKaufmann** [comment]
> Then can we have the GitHub-flavored markdown to use single line breaks please?

There are other renderers — like the _GitHub Flavored Markdown_ Extension from [goldmark](https://github.com/yuin/goldmark) — that also implement the spec. And I don't want to break those.

Right now, it seems like its only github.com that causes the problem...

**Comment by suntong** [comment]
NP, I'd love to, since it works well for you, and also because I'd agree with you that such feature might never be accepted here. So, send the PR pls.

**Comment by zturtleman** [comment]
Expanding on a previous comment (https://github.com/JohannesKaufmann/html-to-markdown/issues/40#issuecomment-1233284205):

From the [official Markdown specification](https://daringfireball.net/projects/markdown/syntax#p):
> When you _do_ want to insert a \<br /\> break tag using Markdown, you end a line with two or more spaces, then type return.

Converting this HTML to Markdown:
```
<p>Line 1<br />Line 2<br />Line 3</p>
```

Should be this Markdown (with two spaces at the end of the first two lines where the \<br /\> tags were):
```
Line 1  
Line 2  
Line 3
```

Using + to visual spaces, it would look like this:

```
Line 1++
Line 2++
Line 3
```

Though the Markdown itself should use spaces, not +.

----

This works on GitHub, CommonMark, and 27 implementations on babelmark.

The reference Markdown (note the two spaces at the end of the first two lines):
```
Line 1  
Line 2  
Line 3
```

GitHub:

Line 1  
Line 2  
Line 3

CommonMark ([web demo](https://spec.commonmark.org/dingus/?text=Line%201%20%20%0ALine%202%20%20%0ALine%203)):
```
<p>Line 1<br />
Line 2<br />
Line 3</p>
```

![Screenshot from 2024-05-25 18-11-14](https://github.com/JohannesKaufmann/html-to-markdown/assets/405505/a6656254-1021-4b59-bc44-08f9bdf11d90)

babelmark ([web demo](https://babelmark.github.io/?text=Line+1++%0ALine+2++%0ALine+3)):
![Screenshot from 2024-05-25 18-15-27](https://github.com/JohannesKaufmann/html-to-markdown/assets/405505/ad77a10c-0eaa-488a-9e22-ff01a9a510f2)

It seems like the solution for how html-to-markdown should handle \<br /\> tags is to convert \<br /\> tags to two spaces and a new line (\\x20\\x20\\n) rather than one (\\n) or two new lines (\\n\\n). This behavior is defined by the official Markdown specification and it seems well supported by various implementations.

**Comment by JohannesKaufmann** [comment]
On the ["v2" branch](https://github.com/JohannesKaufmann/html-to-markdown/tree/v2) are a lot of improvements — including supporting _hard line breaks_.

With a input of `"Hello<br />World"` it now outputs `"Hello  \nWorld"`. 


It is still experimental but feel free to give it a try. Happy to hear about your experience 😊

I am going to close this issue. If you find anything with the new version, please open a new issue!
