### ISSUE TITLE
Can't use the package, go fails to compile

### ISSUE THREAD

**Issue by nikitavoloboev** [JohannesKaufmann/html-to-markdown#94]
**Describe the bug**

On this [repo](https://github.com/nikitavoloboev/go), I get this:

```
~/src/go main*
❯ 
go get github.com/JohannesKaufmann/html-to-markdown

~/src/go main*
❯ 
go run try/*.go
try/html_to_markdown.go:7:2: no required module provides package github.com/JohannesKaufmann/html-to-markdown; to add it:
        go get github.com/JohannesKaufmann/html-to-markdown

~/src/go main*
❯ 
```

No idea why or how to fix. :(

**Comment by JohannesKaufmann** [comment]
Hi @nikitavoloboev 

The setup with the _multiple_ `go.mod` and `go.work` files looks a bit off. Usually a project has one `go.mod` file.

And (from quickly researching this right now) the workspace feature is mainly used for _replacing_ modules. So it might not be needed in your project. (But take it with a grain of salt, since I haven't used that feature yet.)

I cloned the repo & after removing the `go.work` file it worked 🎉


=> So my advice would be: Have another look at the folder structure & how go projects are usually structured. That is the likely source of the problem 🤷‍♂️
